<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DESKTOP-NIB4TL4" failures="1" tests="2" name="Default test(failed)" time="0.126" errors="0" timestamp="2022-06-25T16:36:51 IST">
  <testcase classname="testNGFailed.f2" name="method6" time="0.031">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testNGFailed.f2.method6(f2.java:10)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- method6 -->
  <testcase classname="testNGFailed.f2" name="method7" time="0.003"/>
  <testcase classname="testNGFailed.f2" name="method8" time="0.0">
    <ignored/>
  </testcase> <!-- method8 -->
  <testcase classname="testNGFailed.f2" name="method10" time="0.0">
    <ignored/>
  </testcase> <!-- method10 -->
  <testcase classname="testNGFailed.f2" name="method9" time="0.0">
    <ignored/>
  </testcase> <!-- method9 -->
</testsuite> <!-- Default test(failed) -->
